---
title: "Airbnb dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(tidyverse)
```

```{r}
airbnb = read_csv("./data/nyc_airbnb.zip") %>%
  clean_names() %>%
  rename(boro = neighbourhood_group) %>%
  filter(boro == "Manhattan", room_type =="Entire home/apt", price > 100 & price < 400)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Boxplot

```{r}
airbnb %>%
  mutate(neighbourhood = forcats::fct_reorder(neighbourhood, price)) %>%
  plot_ly(x = ~neighbourhood, y = ~price, color = ~neighbourhood, colors = "Set2", type = "box") 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Scatterplot

```{r}
airbnb %>% 
  mutate(hover_text = str_c("Price: $", price,"\nRating:", review_scores_location / 2)) %>%
  plot_ly(x = ~longitude, y = ~latitude, color = ~price, text = ~hover_text, type = "scatter", mode = "marker", alpha = 0.5)

```

### Chart C: Barchart

```{r}
airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

